language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_install:
  # For the GCC update:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get update -qq; fi

install:
  # Update the GCC version if on Linux:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install -qq g++-4.9 && export CXX="g++-4.9" && export CC="gcc-4.9"; fi

  # Update Bison and Flex:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get upgrade && sudo apt-get install flex && sudo apt-get install bison; fi
  - if [ $TRAVIS_OS_NAME == osx   ]; then brew update && brew install flex && brew install bison; fi

script:
  - make

