language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_install:
  # For the GCC update below...
  - if [ $TRAVIS_OS_NAME == linux ]; then
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
    fi

install:
  # Update the GCC version if on Linux (needed for C++11 support)
  # and Update/install Bison and Flex.
  - if [ $TRAVIS_OS_NAME == linux ]; then
        sudo apt-get update -qq;
        sudo apt-get install -qq flex;
        sudo apt-get install -qq g++-5;
        wget --no-check-certificate http://ftp.gnu.org/gnu/bison/bison-3.0.4.tar.gz;
        mkdir $HOME/bison;
        tar -xf bison-3.0.4.tar.gz;
        cd bison-3.0.4;
        ./configure --prefix=$HOME/bison;
        make -j 4 install;
        cd $PWD/..;
        export PATH=$HOME/bison/bin:$PATH;
        export CXX="g++-5";
        export CC="gcc-5";
    fi
  # Bison/Flex update on OSX using Brew
  # (need the unlink hack for OSX, see: http://stackoverflow.com/a/29053701/1198654)
  - if [ $TRAVIS_OS_NAME == osx ]; then
        brew update;
        brew install flex;
        brew install bison;
        brew unlink flex;
        brew unlink bison;
        brew link flex  --force;
        brew link bison --force;
    fi

script:
  - flex  -V
  - bison -V
  - make

