
// ================================================================================================
// -*- C++ -*-
// File: compiler.hpp
// Author: Guilherme R. Lampert
// Created on: 06/07/15
// Brief: The Compiler class transforms a Syntax Tree representation into VM bytecode.
// ================================================================================================

#ifndef MOON_COMPILER_HPP
#define MOON_COMPILER_HPP

#include "symbol_table.hpp"
#include "syntax_tree.hpp"
#include "vm.hpp"

namespace moon
{

// ========================================================
// class Compiler:
// ========================================================

class Compiler final
{
public:

    //
    // Intermediate code representation:
    //

    struct IntermediateInstr final
    {
        union Operand
        {
            const Symbol            * symbol;
            const IntermediateInstr * jumpTarget;
        };

        IntermediateInstr * next;
        Operand             operand;
        std::uint32_t       uid;
        OpCode              op;
    };

    IntermediateInstr * newInstruction(OpCode op);
    IntermediateInstr * newInstruction(OpCode op, const Symbol * symbol);
    IntermediateInstr * newInstruction(OpCode op, const IntermediateInstr * jumpTarget);

    using DataMap        = std::unordered_map<const Symbol            *, std::uint32_t>;
    using InstructionMap = std::unordered_map<const IntermediateInstr *, std::uint32_t>;

    //
    // Compiler interface:
    //

    // Construct with the abstract syntax tree and symbols generated by the Parser.
    Compiler(SymbolTable & symtab, SyntaxTree & ast);

    // Not copyable.
    Compiler(const Compiler &) = delete;
    Compiler & operator = (const Compiler &) = delete;

    // Runs the compilation process to produce bytecode and data that is
    // ready to be run on a moon::VM instance. Might throw compiler errors.
    void compile(VM::DataVector & progData, VM::CodeVector & progCode);

private:

    IntermediateInstr * traverseTreeRecursive(const SyntaxTreeNode * root);
    void intermediateToVM(VM::DataVector & progData, VM::CodeVector & progCode);
    void fixReferences(const IntermediateInstr * instr, VM::DataVector & progData, VM::CodeVector & progCode);

    SymbolTable       & symTable;
    SyntaxTree        & syntTree;

    IntermediateInstr * firstInstr;
    std::uint32_t       nextInstructionId;

    DataMap             dataMapping;
    InstructionMap      instrMapping;
};

} // namespace moon {}

#endif // MOON_COMPILER_HPP
